import { createSim } from '../sim.js';
import { createRng } from '../util.js';
import { defineValley, createManager } from '../strategy.js';
const seed = 'harvest-2';
const world = { seed, economy: {}, land: {}, jobs: {} };
const sim = createSim(world, { rngFor: (n) => createRng(seed, 'simulation', n), emit: () => {}, clockT: () => 0 });
sim.reset(6); sim.virtualT = 6 * 86400;
const { ids } = defineValley(sim.api);
const mgr = createManager(sim, { strategy: 'contractor', rng: createRng(seed, 's'), ids });
mgr.setup();
const a = sim.api;
const byType = {}; const seen = new Set();
sim.fastForward(6, 6 + 71, (d) => { mgr.day(d); for (const j of a.jobs()) { if (seen.has(j.id)) continue; seen.add(j.id); (byType[j.type] = byType[j.type] || { n: 0, pay: 0, h: 0 }); byType[j.type].n++; byType[j.type].pay += j.pay; } });
console.log(world.jobs.stats, 'done', mgr.stats.jobsDone);
for (const [k, v] of Object.entries(byType)) console.log(k.padEnd(12), v.n, 'avg pay', Math.round(v.pay / v.n));
